Repository PaperMC/Velocity, pull requests merged in 2021-04, with the labels that each got.

#455 Fix one more case of a possibly swallowed exception
  proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java
Labels: bug

#445 Add Duration-accepting methods to TaskBuilder
  api/src/main/java/com/velocitypowered/api/scheduler/Scheduler.java
Labels: enhancement

#456 Fix Forge/Client Proxy Connections mismatch in config
  proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
Labels: bug

#454 Added ListenerBoundEvent and ListenerCloseEvent.
  api/src/main/java/com/velocitypowered/api/event/proxy/ListenerBoundEvent.java
  api/src/main/java/com/velocitypowered/api/event/proxy/ListenerCloseEvent.java
  api/src/main/java/com/velocitypowered/api/network/ListenerType.java
  proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java
  proxy/src/main/java/com/velocitypowered/proxy/network/Endpoint.java
Labels: enhancement

#471 Fix the automatic registration of main plugin event listeners.
  proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
  proxy/src/main/java/com/velocitypowered/proxy/event/VelocityEventManager.java
Labels: bug

#467 feat: nb_NO and nn_NO localisation
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_nb_NO.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_nn_NO.properties
Labels: localization
