Repository PaperMC/Velocity, pull requests merged in 2021-05, with the labels that each got.

#490 Fixed copyright year in /velocity version
  proxy/src/main/java/com/velocitypowered/proxy/command/builtin/VelocityCommand.java
Labels: bug

#492 Do not copy memory in case when packet needs to compress
  proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java
  proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftCompressorAndLengthEncoder.java
  proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftVarintLengthEncoder.java
  proxy/src/test/java/com/velocitypowered/proxy/protocol/ProtocolUtilsTest.java
Labels: enhancement

#493 Further packet handling performance improvements
  proxy/src/main/java/com/velocitypowered/proxy/connection/MinecraftConnection.java
  proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java
  proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftCompressEncoder.java
  proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftCompressorAndLengthEncoder.java
  proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftVarintLengthEncoder.java
  proxy/src/test/java/com/velocitypowered/proxy/protocol/ProtocolUtilsTest.java
Labels: enhancement

#495 Dutch translations
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_nl.properties
Labels: localization

#473 Add fi_FI translations.
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_fi_FI.properties
Labels: localization

#498 Reimplement #434 but aligned to the Velocity 2.0.0 API
  api/src/main/java/com/velocitypowered/api/event/connection/ConnectionHandshakeEvent.java
  api/src/main/java/com/velocitypowered/api/event/connection/ConnectionHandshakeEventImpl.java
  proxy/build.gradle
  proxy/src/main/java/com/velocitypowered/proxy/connection/MinecraftConnection.java
  proxy/src/main/java/com/velocitypowered/proxy/connection/client/HandshakeSessionHandler.java
  proxy/src/main/java/com/velocitypowered/proxy/connection/client/InitialInboundConnection.java
  proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java
Labels: enhancement

#497 New Crowdin updates
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_ar_SA.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_cs_CZ.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_da_DK.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_de_DE.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_es_ES.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_et_EE.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_fi_FI.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_fr_FR.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_he_IL.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_hu_HU.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_it_IT.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_ja_JP.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_ko_KR.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_nb_NO.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_nl_NL.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_nn_NO.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_pl_PL.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_ru_RU.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_sk_SK.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_sq_AL.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_sr_CS.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_sv_SE.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_tl_PH.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_tr_TR.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_zh_CN.properties
  proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_zh_HK.properties
Labels: localization

#499 [2.0] Document some restrictions in the command API
  api/src/main/java/com/velocitypowered/api/command/BrigadierCommand.java
  api/src/main/java/com/velocitypowered/api/command/Command.java
  api/src/main/java/com/velocitypowered/api/command/CommandManager.java
  api/src/main/java/com/velocitypowered/api/command/CommandMeta.java
  api/src/main/java/com/velocitypowered/api/command/ConsoleCommandSource.java
  api/src/main/java/com/velocitypowered/api/command/InvocableCommand.java
Labels: enhancement

#505 Fix bStats error when starting in dev.
  proxy/src/main/java/com/velocitypowered/proxy/Metrics.java
Labels: bug

#504 Simplify EventTask. Add Continuation parameter support.
  annotation-processor/src/main/java/com/velocitypowered/annotationprocessor/ApiAnnotationProcessor.java
  api/src/main/java/com/velocitypowered/api/event/EventTask.java
  proxy/build.gradle
  proxy/src/main/java/com/velocitypowered/proxy/event/CustomHandlerAdapter.java
  proxy/src/main/java/com/velocitypowered/proxy/event/UntargetedEventHandler.java
  proxy/src/main/java/com/velocitypowered/proxy/event/VelocityEventManager.java
  proxy/src/main/java/com/velocitypowered/proxy/plugin/PluginClassLoader.java
  proxy/src/test/java/com/velocitypowered/proxy/event/EventTest.java
Labels: enhancement

#507 Remove Add-Opens from manifest
  proxy/build.gradle
Labels: enhancement
